name: pyspextool_3.11
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - astropy=5.3.1=py311hb49d859_0
  - astroquery=0.4.6=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - brotli=1.0.9=h1a8c8d9_9
  - brotli-bin=1.0.9=h1a8c8d9_9
  - brotli-python=1.0.9=py311ha397e9f_9
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2023.5.7=hf0a4a13_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.1.0=py311he4fd1f5_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - exceptiongroup=1.1.2=pyhd8ed1ab_0
  - fonttools=4.41.1=py311heffc1b2_0
  - freetype=2.12.1=hd633e50_1
  - html5lib=1.1=pyh9f0ad1d_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - keyring=24.2.0=py311h267d04e_0
  - kiwisolver=1.4.4=py311hd6ee22a_1
  - lcms2=2.15=hd835a16_1
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=17_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_9
  - libbrotlidec=1.0.9=h1a8c8d9_9
  - libbrotlienc=1.0.9=h1a8c8d9_9
  - libcblas=3.9.0=17_osxarm64_openblas
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.18=h1a8c8d9_0
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=12_3_0_hd922786_0
  - libgfortran5=12.3.0=ha3a6a3e_0
  - libjpeg-turbo=2.1.5.1=h1a8c8d9_0
  - liblapack=3.9.0=17_osxarm64_openblas
  - libopenblas=0.3.23=openmp_hc731615_0
  - libpng=1.6.39=h76d750c_0
  - libsqlite=3.42.0=hb31c410_0
  - libtiff=4.5.1=h23a1a89_0
  - libwebp-base=1.3.1=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=16.0.6=h1c12783_0
  - matplotlib=3.7.2=py311ha1ab1f8_0
  - matplotlib-base=3.7.2=py311h3bc9839_0
  - more-itertools=9.1.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h7ea286d_0
  - numpy=1.25.1=py311hb8f3215_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.1.1=h53f4e23_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py311h9e438b8_1
  - pillow=10.0.0=py311h095fde6_0
  - pip=23.2=pyhd8ed1ab_0
  - platformdirs=3.9.1=pyhd8ed1ab_0
  - pluggy=1.2.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - pthread-stubs=0.4=h27ca646_1001
  - pyerfa=2.0.0.3=py311h4add359_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.0=pyhd8ed1ab_0
  - python=3.11.4=h47c9636_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyvo=1.4.1=pyhd8ed1ab_0
  - pyyaml=6.0=py311he2be06e_5
  - readline=8.2=h92ec313_1
  - requests=2.31.0=pyhd8ed1ab_0
  - scipy=1.11.1=py311h93d07a4_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.2=py311heffc1b2_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - wheel=0.40.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zipp=3.16.2=pyhd8ed1ab_0
  - zstd=1.5.2=h4f39d0f_7
  - pip:
    - git-lfs==1.6
