name: pyspextool
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - astropy
  - astroquery
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - specutils
  - pip:
    - git-lfs