name: pyspextool_3.11
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - python=3.11
  - astropy
  - astroquery
  - jinja2
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - specutils
  - dust_extinction
  - pip:
    - git-lfs
